---
- name: Ensure storage directory
  file:
    state: directory
    path: "{{ vmstorage_storage_dir }}"
    mode: 0755
    owner: root
    group: root

- name: Start docker vmstorage container
  community.docker.docker_compose_v2:
    state: present
    project_name: vmstorage
    definition:
      services:
        vmstorage:
          image: "{{ vmstorage_docker_image }}"
          container_name: "{{ vmstorage_container_name }}"
          command: "{{ vmstorage_command }}"
          ports: "{{ vmstorage_ports }}"
          volumes:
            - "{{ vmstorage_storage_dir }}:/storage"
          hostname: "{{ vmstorage_container_name }}"
          restart: always
          labels: "{{ vmstorage_docker_labels }}"
      networks:
        default:
          external: true
          name: "{{ vmstorage_docker_network_name }}"
  when: not vmstorage_swarm_cluster or vm_swarm_manager is undefined

- name: Deploy vmstorage to docker swarm
  block:
    - name: Ensure pip installation
      package:
        name: "python3-pip"
        state: present

    - name: Install newer version of pip itself
      pip:
        name: "pip"
        state: latest
        executable: pip3
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version != 24

    - name: Install jsondiff from pip
      pip:
        name: "jsondiff"
        state: present
        executable: pip3
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version != 24

    - name: Ensure jsondiff
      package:
        name: "python3-jsondiff"
        state: present
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version == 24

    - name: Deploy docker vmstorage container in swarm
      community.docker.docker_stack:
        state: present
        name: "{{ vmstorage_stack_name }}"
        with_registry_auth: yes
        compose:
          - version: '3.5'
            services:
              vmstorage:
                image: "{{ vmstorage_docker_image }}"
                command: "{{ vmstorage_command }}"
                ports: "{{ vmstorage_ports }}"
                volumes:
                  - "{{ vmstorage_storage_dir }}:/storage"
                hostname: "{{ vmstorage_container_name }}"
                labels: "{{ vmstorage_docker_labels }}"
                deploy: "{{ vmstorage_swarm_deploy }}"
            networks:
              default:
                external:
                  name: "{{ vmstorage_docker_network_name }}"
      run_once: True
  delegate_to: "{{ vm_swarm_manager }}"
  when:
    - vmstorage_swarm_cluster
    - vm_swarm_manager is defined
